# Generated by Django 3.2.8 on 2021-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sroominfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('Roomcode', models.CharField(max_length=7)),
                ('roomname', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=15)),
                ('roomdesc', models.CharField(max_length=200)),
            ],
        ),
    ]
