# Generated by Django 3.1.7 on 2021-09-12 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('passwords', models.CharField(max_length=50)),
                ('token', models.CharField(default=None, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('passwords', models.CharField(max_length=100)),
                ('Activate', models.BooleanField(default=False)),
                ('token', models.CharField(default=None, max_length=70)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 9, 12, 12, 1, 54, 833198))),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('passwords', models.CharField(max_length=50)),
                ('token', models.CharField(default=None, max_length=70)),
                ('Activate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 9, 12, 12, 1, 54, 833198))),
            ],
        ),
    ]
