# Generated by Django 3.2.5 on 2021-08-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210722_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_info',
            name='isAuthenticated',
            field=models.BooleanField(default=False),
        ),
    ]
