# Generated by Django 3.1.7 on 2021-09-12 06:31

from django.db import migrations, models
import teachl.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomCode', models.CharField(max_length=15)),
                ('Tpoicname', models.CharField(max_length=50)),
                ('Tpoicdescrip', models.CharField(max_length=200)),
                ('UniqCode', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='contends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomCode', models.CharField(max_length=7)),
                ('UniqCode', models.CharField(max_length=10)),
                ('pdf', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='otherlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomCode', models.CharField(max_length=7)),
                ('UniqCode', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='roominfo',
            fields=[
                ('Email', models.CharField(max_length=50)),
                ('Roomcode', models.CharField(default=teachl.models.gencode, max_length=7, primary_key=True, serialize=False)),
                ('roomname', models.CharField(max_length=100)),
                ('url', models.CharField(default=teachl.models.urlcode, max_length=15)),
                ('roomdesc', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tempuploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadfile', models.FileField(upload_to='media')),
                ('tcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='youtubelink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomCode', models.CharField(max_length=7)),
                ('UniqCode', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
