# Generated by Django 3.2.5 on 2021-07-22 03:58

from django.db import migrations, models
import teachl.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roominfo',
            fields=[
                ('Email', models.CharField(max_length=50, unique=True)),
                ('roomcode', models.CharField(default=teachl.models.gencode, max_length=7, primary_key=True, serialize=False)),
                ('roomname', models.CharField(max_length=100)),
                ('roomdesc', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
