# Generated by Django 3.2.5 on 2021-08-28 06:15

from django.db import migrations, models
import teachl.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachl', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='roomcode',
            field=models.CharField(default=teachl.models.gencode, max_length=7),
        ),
    ]
